#!/bin/bash

# Cloudflare Pages Deployment Script for StanShareAI
# This script prepares and documents the deployment process

echo "🚀 StanShareAI - Cloudflare Pages Deployment Guide"
echo "=================================================="
echo ""
echo "Repository: https://github.com/abhijitghoshin/StanShareAI"
echo "Current Commit: $(cd /Users/abhijitghosh/StanShareAI && git rev-parse --short HEAD)"
echo "Branch: main"
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo "=================================================="
echo ""
echo "STEP 1: Go to Cloudflare Dashboard"
echo "  URL: https://dash.cloudflare.com"
echo "  Login with your Cloudflare account"
echo ""
echo "STEP 2: Navigate to Pages"
echo "  Left sidebar → 'Pages' → 'Create a project'"
echo ""
echo "STEP 3: Connect GitHub"
echo "  Click 'Connect to Git'
  → Select GitHub account
  → Authorize Cloudflare access
  → Search for: 'StanShareAI'
  → Select: abhijitghoshin/StanShareAI"
echo ""
echo "STEP 4: Configure Build Settings"
echo "  Project name: stanshareai (or your choice)"
echo "  Production branch: main"
echo "  Framework preset: None (static site)"
echo "  Build command: (leave empty)"
echo "  Build output directory: . (root)"
echo "  Environment variables: (none needed)"
echo ""
echo "STEP 5: Deploy"
echo "  Click 'Save and Deploy'"
echo "  Wait 1-2 minutes for deployment to complete"
echo ""
echo "✅ Your site will be live at:"
echo "  https://stanshareai.pages.dev"
echo ""
echo "STEP 6: Configure Custom Domain (www.stanshare.com)"
echo "  After deployment:"
echo "  1. Pages → Project Settings → Custom domains"
echo "  2. Click 'Set up a custom domain'"
echo "  3. Enter: www.stanshare.com"
echo "  4. Add DNS CNAME record in your registrar:"
echo "     Name: www"
echo "     Type: CNAME"
echo "     Value: stanshareai.pages.dev"
echo "     TTL: Auto"
echo "  5. Wait 5-10 minutes for SSL certificate"
echo ""
echo "🔧 POST-DEPLOYMENT CONFIGURATION:"
echo "=================================================="
echo ""
echo "Update Backend API URLs (for production):"
echo ""
echo "Files to update:"
echo "  - extraction-dashboard.html (line ~280)"
echo "  - funds-dashboard.html (line ~290)"
echo "  - scheduler-dashboard.html (line ~335)"
echo "  - quality-dashboard.html (line ~355)"
echo "  - login.html (if needed)"
echo ""
echo "Change FROM:"
echo "  const apiClient = new StanShareAPIClient('http://localhost:5000');"
echo ""
echo "Change TO:"
echo "  const apiClient = new StanShareAPIClient('https://api.stanshare.com');"
echo ""
echo "Then commit and push:"
echo "  git add *.html"
echo "  git commit -m 'Update: Use production API URL'"
echo "  git push origin main"
echo ""
echo "Cloudflare will auto-redeploy in 1-2 minutes."
echo ""
echo "📊 MONITORING:"
echo "=================================================="
echo ""
echo "After deployment, monitor at:"
echo "  • Cloudflare Pages dashboard"
echo "  • View analytics and performance"
echo "  • Check deployment logs"
echo "  • Monitor for errors"
echo ""
echo "✅ DEPLOYMENT CHECKLIST:"
echo "=================================================="
echo ""
echo "Before going live:"
echo "  ☐ Verify all files are on GitHub (main branch)"
echo "  ☐ Connect GitHub to Cloudflare Pages"
echo "  ☐ Set build output directory to . (root)"
echo "  ☐ Wait for initial deployment"
echo "  ☐ Test temporary domain (stanshareai.pages.dev)"
echo "  ☐ Add custom domain (www.stanshare.com)"
echo "  ☐ Configure DNS CNAME record"
echo "  ☐ Wait for SSL certificate (5-10 min)"
echo "  ☐ Test production URL (https://www.stanshare.com)"
echo "  ☐ Update API URLs in code"
echo "  ☐ Re-deploy with production URLs"
echo ""
echo "=================================================="
echo "🎉 Ready to deploy! Visit: https://dash.cloudflare.com"
echo "=================================================="
